version: '3'

services:
  echo.server:
    image: echo.server20
    build:
      context: .
      dockerfile: DotNetty.Repro.Server/Dockerfile
    ports:
      - '1099:1099'

  echo.client:
    image: echo.client20
    build:
      context: .
      dockerfile: DotNetty.Repro.Client/Dockerfile
    environment:
      DOTNETTY_REPRO_HOST: echo.server
    depends_on:
      - "echo.server"